title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi my name is mohit

# social links
twitter_username: mohit@twitter.com # DO NOT include the @ character, or else the build will fail!
github_username:  mohitmahi004@github.come # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
