theme: minima
title: Mohit's Website
author: Mohit Mahi
email: mohit@inertialelements.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Mohit Website 

# social links
twitter_username: mohit@twitter.com # DO NOT include the @ character, or else the build will fail!
github_username:  mohitmahi004@github.com # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
